version: '3'
services:
  http_server:
    container_name: http-server
    build: ./http-server
    volumes:
      - ./http-server/nginx.config:/etc/nginx/sites-enabled/default
      - ./web-client/app/static:/srv/static
    ports:
      - "80:80"
      - "443:443"
    
  web_client:
    container_name: web-client
    build: ./web-client
    environment:
      - HOST_URL=http://localhost
      - API_URL=http://localhost/api
    volumes:
      - ./web-client/app/source:/srv/app/source
      - ./web-client/app/static:/srv/app/static
      - ./web-client/app/webpack.config.js:/srv/app/webpack.config.js
    restart: always
    working_dir: /srv/app
    command: yarn webpack --watch
